config/routes.rb
Rails.application.routes.draw do
  resources :promotions
  resources :carts
  resources :products

  get 'sessions/new'
  get 'sessions/index'
  resources :users

  root 'sessions#index'       #Alterar Para página certa

  

  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :name, presence: true, length: {maximum: 50}
    validates :password, presence: true, length: {minimum: 6}
    validates :email, presence: true
    before_save {self.email = email.downcase}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, except: [:new, :create]

  def new
    if logado?
      redirect_to sessions_index_path
    end
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if(@user.save)
      redirect_to @user, notice: "Usuário criado com sucesso!"
    else
      render action: :new
    end
  end

  def show
    @user=User.find(params[:id])
  end

  def index
    @users=User.all
  end

  def index_admin

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :address, :phone, :payment_method, :admin)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= form_for current_user do |f| %>
            
            <div class="field">
                <%= f.label :name %>
                <% if current_user.admin? %>
                    <%= f.text_field :name, :value => @user.name %>
                <% else %>
                    <%= f.text_field :name, :value => current_user.name %>
                <% end %>
            </div>
            <div class="field">
                <%= f.label :email %>
                <% if current_user.admin? %>
                    <%= f.email_field :email, :value => @user.email %>
                <% else %>
                    <%= f.email_field :email, :value => current_user.email %>
                <% end %>
            </div>
            <div class="field">
                <%= f.label :password %> 
                <%= f.password_field :password %>
            </div>
            <div class="field">
                <%= f.label :password_confirmation %>
                <%= f.password_field :password_confirmation %>
            </div>
            <div class="field">
                <%= f.label :address %>
                <% if current_user.admin? %>
                    <%= f.text_field :address, :value => @user.address %>
                <% else %>
                    <%= f.text_field :address, :value => current_user.address %>
                <% end %>
            </div>
            <div class="field">
                <%= f.label :phone %>
                <% if current_user.admin? %>
                    <%= f.text_field :phone, :value => @user.phone %>
                <% else %>
                    <%= f.text_field :phone, :value => current_user.phone %>
                <% end %>
            </div>
            <div class="field">
                <%= f.label :payment_method %>
                <br>
                <%= f.radio_button :payment_method, "Dinheiro", :checked => true %> Dinheiro
            </div>
            
            <%= f.hidden_field :admin, :value => false %>

            <div class="actions">
                <%= f.submit "Alterar"%>
            </div>
<% end %>

app/views/users/index.html.erb
<h1>Usuários</h1>

<% if !current_user.admin? %>
    <p>Você não tem permissões suficientes.</p>
<% end %>


<% if current_user.admin? %>
    <% @users.each do |user| %>
        <div>
            <ul>
                <li> <%= user.name %> </li>
                <li> <%= link_to 'Ir para o perfil', user_path(user.id) %> </li>
            </ul>
        </div>
        <br>
    <% end %>
<% end %>

app/views/users/indexadmin.html.erb
<h1>Página do Administrador</h1>

<%= link_to "Ver todos os usuários", users_index_path%>

<%= link_to %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
            <% if @user.errors.any? %>
            <div id="error_explanation">
                        <div class="alert-error">
                                   O formulário contém <%= pluralize(@user.errors.count, "erro") %>.
                        </div>
                        <ul>
                                   <% @user.errors.full_messages.each do |msg| %>
                                   <li><%= msg %></li>
                                   <% end %>
                        </ul>
            </div>
<% end %>
            <div class="field">
                <%= f.label :name %>
                <%= f.text_field :name %>
            </div>
            <div class="field">
                <%= f.label :email %>
                <%= f.email_field :email %>
            </div>
            <div class="field">
                <%= f.label :password %>
                <%= f.password_field :password %>
            </div>
            <div class="field">
                <%= f.label :password_confirmation %>
                <%= f.password_field :password_confirmation %>
            </div>
            <div class="field">
                <%= f.label :address %>
                <%= f.text_field :address %>
            </div>
            <div class="field">
                <%= f.label :phone %>
                <%= f.text_field :phone %>
            </div>
            <div class="field">
                <%= f.label :payment_method %>
                <br>
                <%= f.radio_button :payment_method, "Dinheiro", :checked => true %> Dinheiro
            </div>

            <%= f.hidden_field :admin, :value => false %>

            <div class="actions">
                <%= f.submit "Cadastrar"%>
            </div>
<% end %>

app/views/users/show.html.erb
<%= "Nome: " + @user.name %>
<br>
<%= "Email: " + @user.email %>
<br>
<%= "Endereço: " + @user.address %>
<br>
<%= "Telefone: " + @user.phone %>
<br>
<%= "Método de Pagamento: " + @user.payment_method %>
<br>
<% if @user==current_user or current_user.admin? %>
    <%= link_to "Editar Perfil", edit_user_path %>
<% end %>

<% if current_user.admin? %>
    <br>
    <%= link_to "Ver Usuários", users_path %>
<% end %>