config/routes.rb
Rails.application.routes.draw do
  resources :promotions
  resources :carts
  resources :products

  get 'sessions/new'
  get 'sessions/index'
  resources :users

  root 'sessions#index'       #Alterar Para página certa

  

  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/promotion.rb
class Promotion < ApplicationRecord
    has_many :carts, through: :promotions_cart
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  before_action :set_promotion, only: [:show, :edit, :update, :destroy]

  # GET /promotions
  # GET /promotions.json
  def index
    @promotions = Promotion.all
  end

  # GET /promotions/1
  # GET /promotions/1.json
  def show
  end

  # GET /promotions/new
  def new
    @promotion = Promotion.new
  end

  # GET /promotions/1/edit
  def edit
  end

  # POST /promotions
  # POST /promotions.json
  def create
    @promotion = Promotion.new(promotion_params)

    respond_to do |format|
      if @promotion.save
        format.html { redirect_to @promotion, notice: 'Promotion was successfully created.' }
        format.json { render :show, status: :created, location: @promotion }
      else
        format.html { render :new }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promotions/1
  # PATCH/PUT /promotions/1.json
  def update
    respond_to do |format|
      if @promotion.update(promotion_params)
        format.html { redirect_to @promotion, notice: 'Promotion was successfully updated.' }
        format.json { render :show, status: :ok, location: @promotion }
      else
        format.html { render :edit }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promotions/1
  # DELETE /promotions/1.json
  def destroy
    @promotion.destroy
    respond_to do |format|
      format.html { redirect_to promotions_url, notice: 'Promotion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promotion
      @promotion = Promotion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def promotion_params
      params.require(:promotion).permit(:name, :price, :description)
    end
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/views/promotions/_form.html.erb
<%= form_with(model: promotion, local: true) do |form| %>
  <% if promotion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(promotion.errors.count, "error") %> prohibited this promotion from being saved:</h2>

      <ul>
      <% promotion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/promotions/edit.html.erb
<h1>Editing Promotion</h1>

<%= render 'form', promotion: @promotion %>

<%= link_to 'Show', @promotion %> |
<%= link_to 'Back', promotions_path %>

app/views/promotions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Promotions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @promotions.each do |promotion| %>
      <tr>
        <td><%= promotion.name %></td>
        <td><%= promotion.price %></td>
        <td><%= promotion.description %></td>
        <td><%= link_to 'Show', promotion %></td>
        <td><%= link_to 'Edit', edit_promotion_path(promotion) %></td>
        <td><%= link_to 'Destroy', promotion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Promotion', new_promotion_path %>

app/views/promotions/new.html.erb
<h1>New Promotion</h1>

<%= render 'form', promotion: @promotion %>

<%= link_to 'Back', promotions_path %>

app/views/promotions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @promotion.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @promotion.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @promotion.description %>
</p>

<%= link_to 'Edit', edit_promotion_path(@promotion) %> |
<%= link_to 'Back', promotions_path %>